import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:go_router/go_router.dart';
import 'package:tkd_saas/features/auth/presentation/bloc/authentication_bloc.dart';

import 'app_routes.dart';

/// Centralized router. Uses `$appRoutes` generated by go_router_builder
/// from the `@TypedGoRoute` annotations in [app_routes.dart].
///
/// Route hierarchy (Flutter PWA served at `/app` base path):
///   `/`                                      → Dashboard
///   `/tournaments/:tournamentId`             → Tournament Detail
///   `/tournaments/:tournamentId/setup`       → Bracket Setup
///   `/tournaments/:tournamentId/brackets/:snapshotId` → Bracket Viewer
///   `/login`                                 → Login
///   `/reset-password`                        → Password Reset
///   `/email-confirmed`                       → Email Confirmed
///   `/download`                              → App Download
///
/// When [AppConfig.isAuthenticationEnabled] is `true`, a [redirect] guard
/// ensures every route is locked behind authentication: unauthenticated
/// users are sent to `/login`, authenticated users are bounced away from
/// `/login` to `/`, and users in password-recovery mode are routed to
/// `/reset-password`.
///
/// When authentication is **disabled** (`authenticationBloc` is `null`),
/// auth-only routes (`/login`, `/reset-password`, `/email-confirmed`) are
/// redirected to the dashboard and all other routes resolve freely.
class AppRouter {
  AppRouter._();

  /// Cached singleton so that `MaterialApp.router` always receives the
  /// same [GoRouter] instance, surviving widget rebuilds without losing
  /// navigation state.
  static GoRouter? _cachedRouter;

  /// Returns the (possibly cached) [GoRouter] for this application.
  ///
  /// On first call the router is created and cached; subsequent calls
  /// return the same instance.
  static GoRouter createRouter({AuthenticationBloc? authenticationBloc}) {
    if (_cachedRouter != null) return _cachedRouter!;

    _cachedRouter = GoRouter(
      initialLocation: RoutePaths.dashboard,
      debugLogDiagnostics: false,
      routes: $appRoutes,

      refreshListenable: authenticationBloc != null
          ? _AuthenticationRefreshListenable(authenticationBloc)
          : null,

      redirect: authenticationBloc == null
          ? (_, GoRouterState state) {
              const Set<String> authOnlyPaths = {
                RoutePaths.login,
                RoutePaths.resetPassword,
                RoutePaths.emailConfirmed,
              };
              if (authOnlyPaths.contains(state.matchedLocation)) {
                return RoutePaths.dashboard;
              }
              return null;
            }
          : (_, GoRouterState state) {
              final AuthenticationState authState = authenticationBloc.state;
              final String currentLocation = state.matchedLocation;

              final bool isAuthenticated =
                  authState is AuthenticationAuthenticated;
              final bool isOnLoginPage = currentLocation == RoutePaths.login;
              final bool isOnResetPasswordPage =
                  currentLocation == RoutePaths.resetPassword;
              final bool isOnEmailConfirmedPage =
                  currentLocation == RoutePaths.emailConfirmed;
              final bool isInPasswordRecovery =
                  authState is AuthenticationPasswordRecoveryInProgress;
              final bool isEmailJustConfirmed =
                  authState is AuthenticationEmailJustConfirmed;

              // Public routes that do not require authentication.
              const Set<String> publicPaths = {
                RoutePaths.appDownload,
              };
              final bool isOnPublicPage =
                  publicPaths.contains(currentLocation);

              if (authState is AuthenticationUnknown) return null;

              // Always allow public routes regardless of auth state.
              if (isOnPublicPage) return null;

              if (isEmailJustConfirmed && !isOnEmailConfirmedPage) {
                return RoutePaths.emailConfirmed;
              }

              if (isInPasswordRecovery && !isOnResetPasswordPage) {
                return RoutePaths.resetPassword;
              }

              if (!isAuthenticated &&
                  !isOnLoginPage &&
                  !isInPasswordRecovery &&
                  !isEmailJustConfirmed &&
                  !isOnResetPasswordPage) {
                return RoutePaths.login;
              }

              if (isAuthenticated &&
                  (isOnLoginPage ||
                      isOnResetPasswordPage ||
                      isOnEmailConfirmedPage)) {
                return RoutePaths.dashboard;
              }

              return null;
            },
    );

    return _cachedRouter!;
  }

  /// Resets the cached router. Used exclusively by tests to ensure each
  /// test gets a fresh instance.
  @visibleForTesting
  static void resetForTesting() => _cachedRouter = null;
}

/// Converts the [AuthenticationBloc] stream into a [ChangeNotifier] that
/// [GoRouter.refreshListenable] can subscribe to.
///
/// Every time the BLoC emits a new state, [notifyListeners] is called so
/// the router re-evaluates all redirect guards.
class _AuthenticationRefreshListenable extends ChangeNotifier {
  _AuthenticationRefreshListenable(AuthenticationBloc authenticationBloc) {
    _subscription = authenticationBloc.stream.listen((_) {
      notifyListeners();
    });
  }

  late final StreamSubscription<AuthenticationState> _subscription;

  @override
  void dispose() {
    _subscription.cancel();
    super.dispose();
  }
}
