import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:go_router/go_router.dart';
import 'package:tkd_saas/features/auth/presentation/bloc/authentication_bloc.dart';

import 'app_routes.dart';

/// Centralized router. Uses `$appRoutes` generated by go_router_builder
/// from the `@TypedGoRoute` annotations in [app_routes.dart].
///
/// A [redirect] guard ensures every route is locked behind authentication:
/// unauthenticated users are sent to `/login`, and authenticated users are
/// bounced away from `/login` to `/`.
class AppRouter {
  AppRouter._();

  /// Cached singleton so that `MaterialApp.router` always receives the
  /// same [GoRouter] instance, surviving widget rebuilds without losing
  /// navigation state.
  static GoRouter? _cachedRouter;

  /// Returns the (possibly cached) [GoRouter] for this application.
  ///
  /// On first call the router is created and cached; subsequent calls
  /// return the same instance.
  static GoRouter createRouter({
    required AuthenticationBloc authenticationBloc,
  }) {
    if (_cachedRouter != null) return _cachedRouter!;

    _cachedRouter = GoRouter(
      initialLocation: '/',
      debugLogDiagnostics: false,
      routes: $appRoutes,

      // Re-evaluate redirects whenever the auth state changes.
      refreshListenable: _AuthenticationRefreshListenable(authenticationBloc),

      redirect: (_, GoRouterState state) {
        final AuthenticationState authState = authenticationBloc.state;

        final bool isAuthenticated =
            authState is AuthenticationAuthenticated;
        final bool isOnLoginPage =
            state.matchedLocation == '/login';

        // Still checking session — don't redirect yet.
        if (authState is AuthenticationUnknown) return null;

        // Not authenticated → force to login (unless already there).
        if (!isAuthenticated && !isOnLoginPage) return '/login';

        // Authenticated but lingering on login → send to dashboard.
        if (isAuthenticated && isOnLoginPage) return '/';

        // All other cases — let the route resolve normally.
        return null;
      },
    );

    return _cachedRouter!;
  }

  /// Resets the cached router. Used exclusively by tests to ensure each
  /// test gets a fresh instance.
  @visibleForTesting
  static void resetForTesting() => _cachedRouter = null;
}

// ─────────────────────────────────────────────────────────────────────────────
// GoRouter ↔ BLoC bridge
// ─────────────────────────────────────────────────────────────────────────────

/// Converts the [AuthenticationBloc] stream into a [ChangeNotifier] that
/// [GoRouter.refreshListenable] can subscribe to.
///
/// Every time the BLoC emits a new state, [notifyListeners] is called so
/// the router re-evaluates all redirect guards.
class _AuthenticationRefreshListenable extends ChangeNotifier {
  _AuthenticationRefreshListenable(AuthenticationBloc authenticationBloc) {
    _subscription = authenticationBloc.stream.listen((_) {
      notifyListeners();
    });
  }

  late final StreamSubscription<AuthenticationState> _subscription;

  @override
  void dispose() {
    _subscription.cancel();
    super.dispose();
  }
}
